openapi: 3.0.0
info:
  version: 2018-11-14
  x-release: v4
  title: AWS MediaConnect Bridges Entitlements API
  description: API for AWS Elemental MediaConnect
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: mediaconnect
  x-aws-signingName: mediaconnect
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/mediaconnect-2018-11-14.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://mediaconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS MediaConnect multi-region endpoint
- url: https://mediaconnect.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS MediaConnect multi-region endpoint
- url: http://mediaconnect.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS MediaConnect endpoint for China (Beijing) and China (Ningxia)
- url: https://mediaconnect.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS MediaConnect endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Entitlements
paths:
  /v1/entitlements:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListEntitlements
      description: Displays a list of all entitlements that have been granted to this account. This request returns 20 results per page.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEntitlementsResponse'
              examples:
                ListEntitlements200Example:
                  summary: Default ListEntitlements 200 response
                  x-microcks-default: true
                  value:
                    Entitlements: example-value
                    NextToken: example-value
        '480':
          description: ServiceUnavailableException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableException'
              examples:
                ListEntitlements480Example:
                  summary: Default ListEntitlements 480 response
                  x-microcks-default: true
                  value:
                    result: success
        '481':
          description: TooManyRequestsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsException'
              examples:
                ListEntitlements481Example:
                  summary: Default ListEntitlements 481 response
                  x-microcks-default: true
                  value:
                    result: success
        '482':
          description: BadRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestException'
              examples:
                ListEntitlements482Example:
                  summary: Default ListEntitlements 482 response
                  x-microcks-default: true
                  value:
                    result: success
        '483':
          description: InternalServerErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorException'
              examples:
                ListEntitlements483Example:
                  summary: Default ListEntitlements 483 response
                  x-microcks-default: true
                  value:
                    result: success
      parameters:
      - name: maxResults
        in: query
        required: false
        description: The maximum number of results to return per API request. For example, you submit a ListEntitlements request with MaxResults set at 5. Although 20 items match your request, the service returns no more than the first 5 items. (The service also returns a NextToken value that you can use to fetch the next batch of results.) The service might return fewer results than the MaxResults value. If MaxResults is not included in the request, the service defaults to pagination with a maximum of 20 results per page.
        schema:
          type: integer
          minimum: 1
          maximum: 1000
        example: 1
      - name: nextToken
        in: query
        required: false
        description: The token that identifies which batch of results that you want to see. For example, you submit a ListEntitlements request with MaxResults set at 5. The service returns the first batch of results (up to 5) and a NextToken value. To see the next batch of results, you can submit the ListEntitlements request a second time and specify the NextToken value.
        schema:
          type: string
        example: example-value
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
        example: example-value
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
        example: example-value
      summary: Amazon MediaConnect List Entitlements
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Entitlements
components:
  schemas:
    __integer:
      type: integer
    ServiceUnavailableException: {}
    BadRequestException: {}
    TooManyRequestsException: {}
    ListEntitlementsResponse:
      type: object
      properties:
        Entitlements:
          allOf:
          - $ref: '#/components/schemas/__listOfListedEntitlement'
          - xml:
              name: entitlements
            description: A list of entitlements that have been granted to you from other AWS accounts.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: nextToken
            description: The token that identifies which batch of results that you want to see. For example, you submit a ListEntitlements request with MaxResults set at 5. The service returns the first batch of results (up to 5) and a NextToken value. To see the next batch of results, you can submit the ListEntitlements request a second time and specify the NextToken value.
    __string:
      type: string
    ListedEntitlement:
      type: object
      required:
      - EntitlementArn
      - EntitlementName
      properties:
        DataTransferSubscriberFeePercent:
          allOf:
          - $ref: '#/components/schemas/__integer'
          - xml:
              name: dataTransferSubscriberFeePercent
            description: Percentage from 0-100 of the data transfer cost to be billed to the subscriber.
        EntitlementArn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: entitlementArn
            description: The ARN of the entitlement.
        EntitlementName:
          allOf:
          - $ref: '#/components/schemas/__string'
          - xml:
              name: entitlementName
            description: The name of the entitlement.
      description: An entitlement that has been granted to you from other AWS accounts.
    InternalServerErrorException: {}
    __listOfListedEntitlement:
      type: array
      items:
        $ref: '#/components/schemas/ListedEntitlement'
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/mediaconnect/
x-hasEquivalentPaths: true
